vich_uploader:
    db_driver: orm

    mappings:
        medias:
            uri_prefix: /medias
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
